name: tstore
channels:
- conda-forge
dependencies:
- contextily
- osmnx
- pip
- python=3.12
- xarray
- xvec=0.3.0
- zarr
- pip:
  - -e .
  - git+https://github.com/martibosch/meteostations-geopy.git@feat-multivar-df#egg=meteostations
