name: ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yml
          environment-name: tstore

      - name: register ipykernel
        run: snakemake -c1 register_ipykernel

      - name: run all target
        run: snakemake -c1 all
